#!/usr/bin/env python3

from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
METADATA = Path(__file__).with_name("bindings.json")

NATIVE_TYPES = {
    "int": "P7_TYPE_INT",
    "bool": "P7_TYPE_BOOL",
    "string": "P7_TYPE_STRING",
    "closure": "P7_TYPE_CLOSURE",
    "foreign": "P7_TYPE_FOREIGN",
}

def generate_p7(metadata: dict) -> str:
    lines = ["// Generated by generator/generate.py. Do not edit.", ""]
    for foreign in metadata["foreign_types"]:
        lines.extend(
            [
                "@foreign(",
                f'    type_tag="{foreign["type_tag"]}",',
                f'    dispatcher="{foreign["dispatcher"]}",',
                f'    finalizer="{foreign["finalizer"]}",',
                ")",
                f'pub proto {foreign["p7_name"]} {{',
                "}",
                "",
            ]
        )

    exposed = [item for item in metadata["functions"] if item.get("expose_p7", True)]
    for function in exposed:
        params = ", ".join(
            f'{param["name"]}: {param["p7"]}' for param in function["params"]
        )
        result = (
            f' -> {function["result_p7"]}' if "result_p7" in function else ""
        )
        lines.extend(
            [
                f'@intrinsic(name="{function["intrinsic"]}")',
                f'fn {function["native_name"]}({params}){result};',
                "",
            ]
        )

    for function in exposed:
        params = ", ".join(
            f'{param["name"]}: {param["p7"]}' for param in function["params"]
        )
        args = ", ".join(param["name"] for param in function["params"])
        result = (
            f' -> {function["result_p7"]}' if "result_p7" in function else ""
        )
        lines.extend(
            [
                f'pub fn {function["public_name"]}({params}){result} {{',
                f'    {function["native_name"]}({args})',
                "}",
                "",
            ]
        )

    return "\n".join(lines)


def generate_pascal(metadata: dict) -> str:
    functions = metadata["functions"]
    lines = [
        "{ Generated by generator/generate.py. Do not edit. }",
        "",
        "function RegisterGeneratedFunctions(Api: PP7HostApi): TP7Status;",
        "var",
    ]
    for index, function in enumerate(functions):
        if function["params"]:
            lines.append(
                f'  Params{index}: array[0..{len(function["params"]) - 1}] of LongWord;'
            )
    lines.append("begin")

    for index, function in enumerate(functions):
        for param_index, param in enumerate(function["params"]):
            lines.append(
                f'  Params{index}[{param_index}] := {NATIVE_TYPES[param["native"]]};'
            )
        params = f"@Params{index}[0]" if function["params"] else "nil"
        result_type = NATIVE_TYPES.get(function.get("result_native", ""), "P7_TYPE_ANY")
        has_result = "True" if "result_native" in function else "False"
        lines.extend(
            [
                "  Result := RegisterFunction(",
                f"    Api, '{function['intrinsic']}', {params}, {len(function['params'])},",
                f"    {result_type}, {has_result}, @{function['callback']}",
                "  );",
                "  if Result <> P7_STATUS_OK then Exit;",
            ]
        )

    for foreign in metadata["foreign_types"]:
        lines.extend(
            [
                "  Result := Api^.RegisterForeignType(",
                "    Api^.Runtime,",
                f"    '{foreign['type_tag']}',",
                f"    '{foreign['finalizer']}'",
                "  );",
                "  if Result <> P7_STATUS_OK then Exit;",
            ]
        )
    lines.extend(["end;", ""])
    return "\n".join(lines)


def main() -> None:
    with METADATA.open(encoding="utf-8") as source:
        metadata = json.load(source)

    outputs = {
        ROOT / "src/mod.p7": generate_p7(metadata),
        ROOT / "native/pascal/generated/registration.inc": generate_pascal(metadata),
    }
    for path, contents in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8")


if __name__ == "__main__":
    main()
