#!/usr/bin/env python3

from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
METADATA = Path(__file__).with_name("bindings.json")

NATIVE_TYPES = {
    "int": "P7_TYPE_INT",
    "i32": "P7_TYPE_I32",
    "u32": "P7_TYPE_U32",
    "bool": "P7_TYPE_BOOL",
    "string": "P7_TYPE_STRING",
    "closure": "P7_TYPE_CLOSURE",
    "foreign": "P7_TYPE_FOREIGN",
}

def generate_p7(metadata: dict) -> str:
    lines = [
        "// Generated by generator/generate.py. Do not edit.",
        "",
        "import std.ffi;",
        "",
        "pub struct Align(ffi.i32) {",
        "    pub None = Self(0);",
        "    pub Top = Self(1);",
        "    pub Bottom = Self(2);",
        "    pub Left = Self(3);",
        "    pub Right = Self(4);",
        "    pub Client = Self(5);",
        "    pub Custom = Self(6);",
        "",
        "    pub fn value(ref self) -> ffi.i32 { self.0 }",
        "}",
        "",
        "pub struct[BitOr, BitAnd, BitXor] Anchors(ffi.u32) {",
        "    pub None = Self(0);",
        "    pub Top = Self(1);",
        "    pub Left = Self(2);",
        "    pub Right = Self(4);",
        "    pub Bottom = Self(8);",
        "",
        "    pub fn bitor(ref self, rhs: Self) -> Self { Self(self.0 | rhs.0) }",
        "    pub fn bitand(ref self, rhs: Self) -> Self { Self(self.0 & rhs.0) }",
        "    pub fn bitxor(ref self, rhs: Self) -> Self { Self(self.0 ^ rhs.0) }",
        "    pub fn contains(ref self, rhs: Self) -> bool {",
        "        (self.0 & rhs.0) == rhs.0",
        "    }",
        "    pub fn bits(ref self) -> ffi.u32 { self.0 }",
        "}",
        "",
        "pub struct Color(ffi.i32) {",
        "    pub Black = Self(0);",
        "    pub White = Self(16777215);",
        "    pub Red = Self(255);",
        "    pub Green = Self(32768);",
        "    pub Blue = Self(16711680);",
        "",
        "    pub fn value(ref self) -> ffi.i32 { self.0 }",
        "}",
        "",
    ]
    for foreign in metadata["foreign_types"]:
        bases = foreign.get("bases", [])
        base_list = f'[{", ".join(bases)}]' if bases else ""
        finalizer = (
            f',\n    finalizer="{foreign["finalizer"]}"'
            if foreign.get("finalizer")
            else ""
        )
        lines.extend(
            [
                "@foreign(",
                f'    type_tag="{foreign["type_tag"]}",',
                f'    dispatcher="{foreign["dispatcher"]}"{finalizer},',
                ")",
                f'pub proto{base_list} {foreign["p7_name"]} {{',
                "}",
                "",
            ]
        )

    exposed = [item for item in metadata["functions"] if item.get("expose_p7", True)]
    for function in exposed:
        params = ", ".join(
            f'{param["name"]}: {param.get("native_p7", param["p7"])}'
            for param in function["params"]
        )
        result = (
            f' -> {function.get("native_result_p7", function["result_p7"])}'
            if "result_p7" in function
            else ""
        )
        lines.extend(
            [
                f'@intrinsic(name="{function["intrinsic"]}")',
                f'fn {function["native_name"]}({params}){result};',
                "",
            ]
        )

    for function in exposed:
        params = ", ".join(
            f'{param["name"]}: {param["p7"]}' for param in function["params"]
        )
        args = ", ".join(param["name"] for param in function["params"])
        args = ", ".join(
            param.get("native_arg", param["name"]) for param in function["params"]
        )
        result = (
            f' -> {function["result_p7"]}' if "result_p7" in function else ""
        )
        lines.extend(
            [
                f'pub fn {function["public_name"]}({params}){result} {{',
                f'    {function.get("result_wrap", "")}{function["native_name"]}({args})'
                + function.get("result_wrap_suffix", ""),
                "}",
                "",
            ]
        )

    return "\n".join(lines)


def generate_pascal(metadata: dict) -> str:
    functions = metadata["functions"]
    lines = [
        "{ Generated by generator/generate.py. Do not edit. }",
        "",
        "function RegisterGeneratedFunctions(Api: PP7HostApi): TP7Status;",
        "var",
    ]
    for index, function in enumerate(functions):
        if function["params"]:
            lines.append(
                f'  Params{index}: array[0..{len(function["params"]) - 1}] of LongWord;'
            )
    lines.append("begin")

    for index, function in enumerate(functions):
        for param_index, param in enumerate(function["params"]):
            lines.append(
                f'  Params{index}[{param_index}] := {NATIVE_TYPES[param["native"]]};'
            )
        params = f"@Params{index}[0]" if function["params"] else "nil"
        result_type = NATIVE_TYPES.get(function.get("result_native", ""), "P7_TYPE_ANY")
        has_result = "True" if "result_native" in function else "False"
        lines.extend(
            [
                "  Result := RegisterFunction(",
                f"    Api, '{function['intrinsic']}', {params}, {len(function['params'])},",
                f"    {result_type}, {has_result}, @{function['callback']}",
                "  );",
                "  if Result <> P7_STATUS_OK then Exit;",
            ]
        )

    for foreign in metadata["foreign_types"]:
        finalizer = (
            f"'{foreign['finalizer']}'" if foreign.get("finalizer") else "nil"
        )
        lines.extend(
            [
                "  Result := Api^.RegisterForeignType(",
                "    Api^.Runtime,",
                f"    '{foreign['type_tag']}',",
                f"    {finalizer}",
                "  );",
                "  if Result <> P7_STATUS_OK then Exit;",
            ]
        )
    lines.extend(["end;", ""])
    return "\n".join(lines)


def main() -> None:
    with METADATA.open(encoding="utf-8") as source:
        metadata = json.load(source)

    outputs = {
        ROOT / "src/mod.p7": generate_p7(metadata),
        ROOT / "native/pascal/generated/registration.inc": generate_pascal(metadata),
    }
    for path, contents in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8")


if __name__ == "__main__":
    main()
